### ISSUE TITLE
Feature request: add support for helm template's `--set-file` parameter

### ISSUE THREAD

**Issue by jfly** [jtyr/kubeconform-helm#25]
In the help, I see the following parameters that get passed to helm template:

```
$ ./scripts/plugin_wrapper.py --help
...
helm template:
  Options passed to the 'helm template' command

  -f FILE, --values FILE
                        values YAML file or URL (can specified multiple)
  -n NAME, --namespace NAME
                        namespace
  -r NAME, --release NAME
                        release name
  CHART                 chart path (e.g. '.')
...
```

What about helm's various `--set` parameters? The particular one I need right now is `--set-file`.

**Comment by jtyr** [comment]
Different values files are automatically loaded from `tests/kubeconform/*-values.yaml` inside the Helm chart directory. The location can be changed via `--values-dir` and the file pattern can be changed via `--values-pattern` command line arguments.
