### ISSUE TITLE
Install fails with plugin metadata (plugin.yaml) missing

### ISSUE THREAD

**Issue by Shreyaskulkarni98** [jtyr/kubeconform-helm#28]
Run `helm plugin install plugins/kubeconform-helm.tar.gz`
Get Error: `plugin metadata (plugin.yaml) missing`

Results of helm version:
`version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}`

**Comment by jtyr** [comment]
Please try to install it the way how it's described here:
https://github.com/jtyr/kubeconform-helm?tab=readme-ov-file#helm-plugin
